"""baseline schema

Revision ID: a1fac97c9bc7
Revises: 
Create Date: 2025-11-04 22:06:48.016756

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a1fac97c9bc7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    op.drop_table('embedding_queue')
    op.drop_column('auth_tokens', 'token_encrypted')
    op.drop_index(op.f('idx_logs_org_created'), table_name='logs')
    op.drop_column('users', 'email_encrypted')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email_encrypted', postgresql.BYTEA(), autoincrement=False, nullable=True))
    op.create_index(op.f('idx_logs_org_created'), 'logs', ['org_id', sa.literal_column('created_at DESC')], unique=False)
    op.add_column('auth_tokens', sa.Column('token_encrypted', postgresql.BYTEA(), autoincrement=False, nullable=True))
    op.create_table('embedding_queue',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('message_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('filename', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('text_content', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('staged_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('embedding_queue_pkey'))
    )
    op.create_table('messages',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('source', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('chat_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('sender', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('timestamp', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('messages_pkey'))
    )
    # ### end Alembic commands ###
